import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <div className='flex justify-between mb-4 p-2 bg-indigo-200'>
        <h1>lets-breathee</h1>
        <div> 
          <Link href={'/'}>HOME </Link>
        </div>
        <div> 
        <Link href={'/product'}>SHOP </Link>
        </div>
        <div>
        <Link href={'/album'}> ALBUM</Link>
        </div>
        <div>
        <Link href={'/blog'}>STORY </Link>
        </div>
        <div>
        <Link href={'/cart'}>CART </Link>
        </div>

      </div>
      {children}
      </body>
      
      
    </html>
  )
}
